---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1.0.rc.0

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[safe_search_test::default]
