name             'safe-search'
maintainer       'Ryan Cragun'
maintainer_email 'ryan@chef.io'
license          'Apache 2.0'
description      'Extends the Chef DSL to include a safe_search function'
long_description 'Extends the Chef DSL to include a safe_search function'
version          '0.1.0'

supports 'amazon'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
supports 'smartos'
supports 'omnios'
supports 'suse'
